export const GET_COURSE_TRAINING = "GET_COURSE_TRAINING";
export const FETCH_COURSE_TRAINING_REQUEST = 'FETCH_COURSE_TRAINING_REQUEST'
export const FETCH_COURSE_TRAINING_FAILURE = 'FETCH_COURSE_TRAINING_FAILURE'


