export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FIALURE = "FILE_UPLOAD_FIALURE";

export const FILE_UPLOAD_MULTI_REQ = "FILE_UPLOAD_MULTI_REQ";
export const FILE_UPLOAD_MULTI_SUCCESS = "FILE_UPLOAD_MULTI_SUCCESS";
export const FILE_UPLOAD_MULTI_FIALURE = "FILE_UPLOAD_MULTI_FIALURE";
