export const GET_CURRICULUM_BY_ID = 'GET_CURRICULUM_BY_ID'

export const GET_CURRICULUM_BY_ID_REQ = 'GET_CURRICULUM_BY_ID_REQ'

export const GET_CURRICULUM_BY_ID_FAILURE = 'GET_CURRICULUM_BY_ID_FAILURE'