export const GET_COURSE_TRAINING_TYPE = "GET_COURSE_TRAINING_TYPE";
export const SEARCH_COURSE_TRAINING_TYPE = "SEARCH_COURSE_TRAINING_TYPE";
export const SEARCH_COURSE_TRAINING_TYPE_REQUEST = "SEARCH_COURSE_TRAINING_TYPE_REQUEST";
export const SEARCH_COURSE_TRAINING_TYPE_FAILURE = "SEARCH_COURSE_TRAINING_TYPE_FAILURE";
export const DELETE_COURSE_TRAINING_TYPE = "DELETE_COURSE_TRAINING_TYPE";
export const POST_COURSE_TRAINING_TYPE = "POST_COURSE_TRAINING_TYPE";
export const UPDATE_COURSE_TRAINING_TYPE = "UPDATE_COURSE_TRAINING_TYPE";
export const FETCH_COURSE_TRAINING_TYPE_REQUEST =
  "FETCH_COURSE_TRAINING_TYPE_REQUEST";
export const FETCH_COURSE_TRAINING_TYPE_FAILURE =
  "FETCH_COURSE_TRAINING_TYPE_FAILURE";
