export const GET_COURSE_TRAINING_TYPE_REQUEST = 'GET_COURSE_TRAINING_TYPE_REQUEST'
export const GET_COURSE_TRAINING_TYPE_SUCCESS = 'GET_COURSE_TRAINING_TYPE_SUCCESS'
export const GET_COURSE_TRAINING_TYPE_FAILURE = 'GET_COURSE_TRAINING_TYPE_FAILURE'
export const GET_ALL_COURSE_TRAINING = 'GET_ALL_COURSE_TRAINING '