export const GET_CAREER_PATH = "GET_CAREER_PATH";
export const POST_CAREER_PATH = "POST_CAREER_PATH";
export const DELETE_CAREER_PATH = "DELETE_CAREER_PATH";
export const UPDATE_CAREER_PATH = "UPDATE_CAREER_PATH";
export const SEARCH_CAREER_PATH = "SEARCH_CAREER-PATH";
export const SEARCH_CAREER_PATH_REQUEST = "SEARCH_CAREER-PATH_REQUEST";
export const SEARCH_CAREER_PATH_FAILURE = "SEARCH_CAREER-PATH_FAILURE";

export const FETCH_CAREER_PATH_REQUEST = "FETCH_CAREER_PATH_REQUEST";
export const FETCH_CAREER_PATH_FAILURE = "FETCH_CAREER_PATH_FAILURE";
