export const GET_ALUMNI = "GET_ALUMNI";
export const POST_ALUMNI = "POST_ALUMNI";
export const DELETE_ALUMNI = "DELETE_ALUMNI";
export const UPDATE_ALUMNI = "UPDATE_ALUMNI";
export const UPDATE_ALUMNI_FAILURE = "UPDATE_ALUMNI_FAILURE";
export const SEARCH_ALUMNI_REQUEST = "SEARCH_ALUMNI_REQUEST";
export const SEARCH_ALUMNI = "SEARCH_ALUMNI";
export const SEARCH_ALUMNI_FAILURE = "SEARCH_ALUMNI_FAILURE";

export const FETCH_ALUMNI_REQUEST = "FETCH_ALUMNI_REQUEST";
export const FETCH_ALUMNI_FAILURE = "FETCH_ALUMNI_FAILURE";
