export const GET_MENU = "GET_MENU";
export const POST_MENU = "POST_MENU";
export const DELETE_MENU = "DELETE_MENU";
export const SEARCH_MENU = "SEARCH_MENU";
export const SEARCH_MENU_REQUEST = "SEARCH_MENU_REQUEST";
export const SEARCH_MENU_FAILURE = "SEARCH_MENU_FAILURE";
export const UPDATE_MENU = "UPDATE_MENU";
export const FETCH_MENU_SUCCUESS = "FETCH_MENU_SUCCUESS";
export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";

export const UPDATE_MENU_REQUEST = 'UPDATE_MENU_REQUEST'
export const UPDATE_MENU_SUCESS = 'UPDATE_MENU_SUCESS'
export const UPDATE_MENU_FAILURE = 'UPDATE_MENU_FAILURE'
