export const GET_USERS = "GET_USERS";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const POST_USER = "POST_USER";
export const UPDATE_USER = "UPDATE_USER";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";
